# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faeae7a3bbdf7756ad7bd7e5eeb63bc56370f241e0d822dd9b82ef0e17dd6c5400653bb563da918ada820fc4a0b609651229c83a8262db4107844a44465773cd

test:
  secret_key_base: f9135c26018826327008af59f0136138fe7c9555bd1d8b15c9bebb5072ab7dc592bd7e5f6e0ab60b0f3b332a7f17850ac9cf9cecb817966f71e69365fa541c0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
